services:
  - type: web
    name: dsbvs-app
    env: python
    buildCommand: pip install -r requirements.txt && python -m textblob.download_corpora  && python -m nltk.downloader all
    runCommand: python app.py 
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production